
version: '3'

services:
    # PHP Service
    app:
        image: php:8.2-fpm
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel
    # Nginx Service
    webserver:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        #    - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - laravel
    # MySQL Service
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: laravel
            MYSQL_PASSWORD: password
        networks:
            - laravel
networks:
    laravel:
