version: '3'

services:
    web:
        build: .
        volumes:
            -   .:/var/www/html
        container_name: pokedexdev
        dns:
            - 8.8.8.8
            - 8.8.4.4
        #        command:
        ports:
            - "5173:5173"
            - "8000:8000"
        expose:
            - "5173"
            - "8000"
        entrypoint: ["/bin/bash", "/usr/local/bin/entrypoint.sh"]
