version: '3'

services:
   web:
        build: .
        container_name: pokedexdev
        dns:
            - 8.8.8.8
            - 8.8.4.4
#        command:
        ports:
            - "5173:5173"
            - "80:80"
            - "8000:8000"
        expose:
       #     - "5173"
       #     - "80"
            - "1-10000"
